name: Security Audit

on:
  schedule:
    - cron: "0 0 * * 1" # Runs every Monday at midnight
  workflow_dispatch:

jobs:
  audit:
    name: Cargo Deny Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      # Uses pre-compiled cargo-deny to check for vulnerabilities
      - name: Run cargo-deny
        uses: EmbarkStudios/cargo-deny-action@v2
        with:
          command: check advisories
          manifest-path: ./core/Cargo.toml
